### ISSUE TITLE
Tow duration processing

### ISSUE THREAD

**Issue by lcgodoy** [afredston/mid_atlantic_forecasts#8]
Hello everyone,

There is a problem in the `01_import_summer_flounder.R` file.
In L75, `haul_dur == NA` does not return `TRUE` nor `FALSE`; it always returns `NA`. 
To test whether a variable is an `NA`, we should use the `is.na()` function.

For example, when running:
```
towdur_raw %>% 
  count(TOWDUR == NA)
```
We get:
```
#>   # A tibble: 1 × 2
#>  `TOWDUR == NA`     n
#>   <lgl>          <int>
#>   1 NA             19102

```

On the other hand, if we run:
```
towdur_raw %>%
  count(is.na(TOWDUR˘))
```

We get:
```
#> # A tibble: 2 × 2
#>   `is.na(TOWDUR)`     n
#>   <lgl>           <int>
#> 1 FALSE           14975
#> 2 TRUE             4127
```

—

Once I modified that line of code (75) to `is.na(haul_dur)`, it dropped 4301 data points (around 22.5%). The main problem is that, by doing so, we lose data from 1981 in the patches with `floor(lat)` equal to 42, 43, and 44.

I hope this helps. Let me know if there is anything I can help with.
Lucas.

**Comment by afredston** [comment]
Lucas, I really appreciate you pointing out this error in the code. I brought it up with Malin because I was surprised this filter (if implemented correctly) would drop so much data. In our discussion I realized that while this filter needed to be applied to the FISHGLOB dataset with which I am now more familiar, it doesn't need to be applied to the older OceanAdapt data used for this project, because adjustments for haul duration happened in the data preparation process. I've removed that part of the code from this script and added a check to show that the quantiles of CPUE are the same whether or not a haul duration is recorded. Thank you!
